### ISSUE TITLE
PA review user auth

### ISSUE THREAD

**Issue by kangstephen94** [kangstephen94/wallstreetbets#2]
- [x] Users can sign up, login and logout
- [x] Users can try a demo of the Webapp
- [x] Adequate Styling
- [x] Smooth, bug-free navigation
- [x] Adequate seed data

**Comment by andywynkoop** [comment]
- [x] Add live link to the wiki page
- [x] Pseudo-selectors should be on the actual clickable link instead of the container. I should only see a hover effect when I hover over something I can click on.
- [x] Social media links should open in a new tab (target="_blank")
- [x] Logo should be clickable and redirect to "/"
- [x] Going to a random route `/#/somethingrandomfdsatbdtzxd` should redirect or display a 404 page
- [x] cursor:pointer on username since it appears clickable
